### ISSUE TITLE
Improvement: transition duration/delay number parsing

### ISSUE THREAD

**Issue by yyx990803** [weexteam/weex-styler#10]
Currently, transition duration/delay such as `0.5s` is preserved as-is. When passed to Weex's animation API which expects number of milliseconds, this seems to be treated as 0.5ms instead (likely via `parseInt`).

We can of course check this in the runtime framework, but ideally `weex-styler` could normalize these durations during the build phase.

**Comment by songsiqi** [comment]
@yyx990803 OK. The unit `s` could be formatted to `ms`. Is it necessary to delete `ms` unit?

**Comment by yyx990803** [comment]
Normalizing durations into integers would be nice.
